### ISSUE TITLE
Win7 Ultimate SP1 x64 missing api-ms-win-core-path-l1-1.0.dll

### ISSUE THREAD

**Issue by Ipokrit** [d0ng1er/advanced_cartography#2] opened 2020-12-20 06:42 UTC
When I try to create a map using "stitcher.exe", I get the system error «The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem».
I also get the following error window:
![stitcher_er](https://user-images.githubusercontent.com/47214382/102706650-c920d380-42ce-11eb-9dc5-154dfb7549d6.png)
As far as I could find on the Internet by the name of DLL and understand it, the problem lies in the termination of support operating systems older than Win 8 for Python 3.9? [https://bugs.python.org/issue40740](url)
But at the same time "Dadido3" Stitch from ["noita-mapcap"](https://github.com/Dadido3/noita-mapcap) runs successfully and "stitching" the map. True, only from its own screenshots.

**Comment by d0ng1er** [comment] 2020-12-20 13:56
Yep, I fucked that up. Stitcher.exe is a couple python 3.9 scripts "compiled" with pyinstaller for ease of use. I believe that Dadido3's stitch is an actual batch file, the two are unrelated and work in different ways. I'd forgotten that python 3.9 drops support for windows 8 and below. 

I've fixed the readme, at this point there are a couple options: 
- I'll attempt to rebuild the exe using an older version of python and release it later today. It shouldn't take very long to figure out if this will work or not.
- Advanced Mode: You can take the source scripts (in your mod folder at `advanced_cartography/files/stc`), move them to the root folder (stitcher.py and stitch.py need to be in the main AC folder to find the files) and try to run them using python 3.8 (open cmd in same dir and run python, then `import stitcher' followed by `stitcher.main()`). This might work, if it doesn't work then option one will definitely not work.

Barring those two options (if something in the scripts turns out to be incompatible with python 3.8, which is likely), this might be unfixable, which would suck. I've updated the readme, so hopefully this issue doesn't affect anyone else.

**Comment by d0ng1er** [comment] 2020-12-20 16:44
[rebuilt stitcher.exe](https://github.com/d0ng1er/advanced_cartography/releases/tag/TEST)

Hopefully, if you put this in the folder where stitcher.exe normally goes and run it, it will work (assuming you're running on vista or 7, if your OS is any older than that then there's not much I can do). Please report back with your results.

**Comment by Ipokrit** [comment] 2020-12-20 17:14
Checked the exe file. Error messages:
![stitcher_vista error](https://user-images.githubusercontent.com/47214382/102719356-8be92f80-4328-11eb-8ee7-07d6ab113482.png)
I'm not familiar with Python, so I don't understand the instructions from the "Advanced Mode" yet. There will be time later - I'll try to figure it out.

**Comment by d0ng1er** [comment] 2020-12-20 20:15
This appears to be a fairly old error from a version of PyInstaller used 4 years ago supposedly fixed in 2017, no idea what it's doing here now. 
- https://stackoverflow.com/questions/38674400/missing-dll-files-when-using-pyinstaller
- https://github.com/pyinstaller/pyinstaller/issues/4908 (might also be this)
I've added some of the fixes suggested in there to the [same release](https://github.com/d0ng1er/advanced_cartography/releases/tag/TEST), now in the "v2" exe, hopefully that solves it. If not you could try to find a way to get your terminal window to use a different charset, such as UTF-8, assuming that it's trying to use ANSI.

The good news: I know from running it on my computer that stitcher.py **is** backwards compatible to python 3.8.6, so the mod is most likely not completely broken for anything earlier than windows 8.

**Comment by Ipokrit** [comment] 2020-12-21 05:57
Checked the stitcher_vista_v2.exe. Same error message as above.
Encodings as far as I understand:
 - default CP866, «DOS Cyrillic Russian»;
 - try UTF-8? CP65001 trough `chcp 65001` in console (also checked CP1251, «Windows Cyrillic Russian» and CP1252, «Windows Latin»). Result: same errors as originally in all 3 variants EXE files. No changes.
P.S. The program does not need Python in the system to run, right? I have 3.7.2 but maybe I need upgrade it to 3.8.x?
P.P.S. I'm still trying to understand Python for other instructions...

**Comment by d0ng1er** [comment] 2020-12-21 17:42
It "shouldn't" require python to run. But for some reason, in your case, it ends up looking for something present in the standard python install that's not in the exe itself, even though it should be. The problem is that even when I make sure to add the missing DLL  to the exe, it still doesn't work, which means it's more broken than I thought. It's something to do with with the win7 terminal, ansiicon, pyinstaller, and maybe the PyInquirer module I used in stitcher.py. It's a mess.

Last possible easy fix: try to run stitcher.exe in some terminal program other than cmd, such as powershell. You'd need to open the terminal, `cd` to the AC root folder, and then type `stitcher.exe` (or `./stitcher.exe` for powershell). Try that for both versions. Should look something like this:

![image](https://user-images.githubusercontent.com/70249759/102805727-a7385700-4389-11eb-810e-dc5fc8914e2e.png)

Otherwise, it's entirely possible that the stitch.py script will run fine on 3.7.2. All you would need to do is to run `pip install pillow` to get the PIL module, then copy the `stitch.py` script from `advanced_cartography/files/stc` to the root (`advanced_cartography`) folder, then open up python there, run `import stitch` then `stitch.stitch2(".//raws//[seed]"). You'll be calling the stitch function directly without the CLI, which should run fine. If it doesn't run fine on python 3.7.2, it will run fine on python 3.8.6, probably.

**Comment by Ipokrit** [comment] 2020-12-22 13:31
Try 2 variants EXE files with:
  - PowerShell 2.0 included with the system.
  - Then install [«Windows 10 Universal C Runtime»](https://www.microsoft.com/en-us/download/details.aspx?id=50410) + [«Windows Management Framework 5.1 x64»](https://www.microsoft.com/en-us/download/details.aspx?id=54616) (with included PowerShell 5.1).
  - Finally tried [«PowerShell 7.1.0 x64»](https://github.com/PowerShell/PowerShell/releases/download/v7.2.0-preview.2/PowerShell-7.2.0-preview.2-win-x64.zip).
 
No changes. Same errors.

**Comment by d0ng1er** [comment] 2020-12-22 18:42
Well, that does suck. At this point I'm at a loss, and your best bet is probably to try and run the python script directly. You don't need to learn *too much* python to do that (really not much at all), and it's almost guaranteed to work (because whatever is causing this is almost certainly part of the CLI/menu, and you'd be skipping that by calling stitch.py directly). So just install pillow into your python version, move stitch.py from the `files/stc` folder to root and then call the function as I explained in last comment. Should look something like this:

![image](https://user-images.githubusercontent.com/70249759/102922096-79bbde00-445b-11eb-97b1-c5cb0e3ef4a8.png)

hope this works.

**Comment by Ipokrit** [comment] 2020-12-24 05:11
Installed PyIniquirer `python -m pip install PyInquirer` to import stitch.Py. It didn't work, _maybe because made a mistake in the stitch.stitch2 () command._
Updated pip v19.0.1 to v20.3.3 to install PyInstaller `pip install PyInstaller.`
Then I encountered an error in the stitch.stitch2 ("**.**// raws // [seed]") command entered in PowerShell 5.1 (in cmd.exe - "No module named 'stitch' on import"). Fixed it and **now script works**.
P.S. The exe files still not worked.

**Comment by d0ng1er** [comment] 2020-12-24 16:31
Glad that at least something is working.

I'm closing this issue. Thanks for bringing it to my attention. It's unfortunate that PyInstaller/PyInquirer seems to cause errors when compiled on windows 10 and run on windows 7. As you improve with python, you may consider trying to PyInstall the script yourself on W7 and see if that works. For now, copy-pasting the command is likely your best bet.

**Closed by d0ng1er** 2020-12-24 16:31 UTC
